import {EXPLAINFIELD} from "@/assets/common/js/global.js";

let json = {
    "title": "管理员",
    "fieldList": [
        {
            "width": "60",
            "key": "id",
            "title": "",
            "type": "selection",
            "length": "10",
            "isRequire": false,
            "regStr": "",
            "message": "",
            "controlType": "hidden",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": true,
            "isWhere": false,
            "javaWhere": "equals",
            "javaType": "integer"
        },
        {
            "key": "tid",
            "title": "字符串ID",
            "type": "html",
            "length": "45",
            "isRequire": false,
            "regStr": "",
            "message": "字符串ID",
            "controlType": "hidden",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": false,
            "isWhere": false,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "account",
            "title": "账号",
            "type": "html",
            "length": "45",
            "isRequire": false,
            "regStr": "",
            "message": "账号",
            "controlType": "input",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": true,
            "isWhere": true,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "phone",
            "title": "手机号",
            "type": "html",
            "length": "15",
            "isRequire": false,
            "regStr": "",
            "message": "手机号",
            "controlType": "input",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": true,
            "isWhere": true,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "nickname",
            "title": "昵称",
            "type": "html",
            "length": "45",
            "isRequire": false,
            "regStr": "",
            "message": "昵称",
            "controlType": "input",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": true,
            "isWhere": true,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "truename",
            "title": "真实姓名",
            "type": "html",
            "length": "45",
            "isRequire": false,
            "regStr": "",
            "message": "真实姓名",
            "controlType": "input",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": true,
            "isWhere": true,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "departmentid",
            "title": "组",
            "type": "html",
            "length": "45",
            "isRequire": false,
            "regStr": "",
            "message": "",
            "controlType": "urlradio",
            "url": "/admin/findAllTDepartment",
            "dataKey": "tid",
            "dataName": "name",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": false,
            "isWhere": false,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "email",
            "title": "邮箱",
            "type": "html",
            "length": "255",
            "isRequire": false,
            "regStr": "",
            "message": "邮箱",
            "controlType": "input",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": true,
            "isWhere": true,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "ip",
            "title": "最后登录IP",
            "type": "html",
            "length": "60",
            "isRequire": false,
            "regStr": "",
            "message": "最后登录IP",
            "controlType": "hidden",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": false,
            "isWhere": false,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "lastlogintime",
            "title": "最后登录时间",
            "type": "html",
            "length": "26",
            "isRequire": false,
            "regStr": "",
            "message": "最后登录时间",
            "controlType": "hidden",
            "max": "",
            "min": "",
            "format": "yyyy-MM-dd HH:mm:ss",
            "isShowColumn": false,
            "isWhere": false,
            "javaWhere": "equals",
            "javaType": "date"
        },
        {
            "key": "canlogintime",
            "title": "允许登录时间",
            "type": "html",
            "length": "26",
            "isRequire": false,
            "regStr": "",
            "message": "允许登录时间",
            "controlType": "hidden",
            "max": "",
            "min": "",
            "format": "yyyy-MM-dd HH:mm:ss",
            "isShowColumn": false,
            "isWhere": false,
            "javaWhere": "equals",
            "javaType": "date"
        },
        {
            "key": "status",
            "title": "状态",
            "slot": "status",
            "length": "10",
            "isRequire": false,
            "regStr": "",
            "message": "状态",
            "controlType": "hidden",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": true,
            "isWhere": true,
            "javaWhere": 'equals',
            "javaType": "integer"
        },
        {
            "key": "createtime",
            "title": "创建时间",
            "type": "html",
            "length": "26",
            "isRequire": false,
            "regStr": "",
            "message": "创建时间",
            "controlType": "hidden",
            "max": "",
            "min": "",
            "format": "yyyy-MM-dd HH:mm:ss",
            "isShowColumn": true,
            "isWhere": false,
            "javaWhere": 'equals',
            "javaType": "date"
        },
        {
            "key": "note",
            "title": "备注",
            "type": "html",
            "length": "255",
            "isRequire": false,
            "regStr": "",
            "message": "备注",
            "controlType": "input",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": true,
            "isWhere": true,
            "javaWhere": "like",
            "javaType": "string"
        },
        {
            "key": "del",
            "title": '是否删除',
            "type": "html",
            "length": "10",
            "isRequire": false,
            "regStr": "",
            "message": "是否删除",
            "controlType": "hidden",
            "max": "",
            "min": "",
            "format": "",
            "isShowColumn": false,
            "isWhere": false,
            "javaWhere": 'equals',
            "javaType": "integer"
        }
    ]
};

//==== 解释json数据
const obj = EXPLAINFIELD(json);
//=====  标题
export const TitleJson = obj.title;
//===== 添加字段
export const addFieldDataJson = obj.addFieldData;
//===== 修改字段
export const updateFieldDataJson = obj.updateFieldData;
//=====  表头
export const TableHeaderJson = obj.TableHeader;
//=====  搜索字段
export const searchWhereJson = obj.searchWhere;


